baseURL = 'http://localhost:1313/'
languageCode = 'ua-ua'
title = 'Мой блог'
theme = 'terminal'

[params]
  # dir name of your blog content (default: `content/posts`).
  # the list of set content will show in your homepage.
  contentTypeName = "posts"

  # ["orange", "blue", "green", "red", "purple"]
  themeColor = "green"

  # show all pages or only posts (default: false)
  showAllPosts = false

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (default: true)
  # showToc = true

  # Show full text of post or only summary (default: true)
  showFullText = true

  # Show social media icons
  # [[params.social]]
  #   name = "twitter"
  #   url = "https://twitter.com/..."

  mainSections = ["post"]
  dateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "О сайте"
    url = "/about"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Статьи"
    url = "/posts"
    weight = 20

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

[build]
  writeStats = true