[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.1"
  NODE_VERSION = "18"
  CF_PAGES_URL = "https://shum-go.buzzler0109.workers.dev/"

[context.production.environment]
  HUGO_ENV = "production"
  CF_PAGES_URL = "https://shum-go.buzzler0109.workers.dev/" 