[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.1"
  NODE_VERSION = "18"
  CF_PAGES_URL = "https://shum-go-terminal.pages.dev/"

[context.production.environment]
  HUGO_ENV = "production"
  CF_PAGES_URL = "https://shum-go-terminal.pages.dev/"
  HUGO_DESTINATION = "public" 